apiVersion: v1
appVersion: "1.0"
home: https://github.com/vivdalal/team2-kubeop-helmChart/s3folder-kubeop-chart
description: kubeop Helm chart for Kubernetes
name: s3folder-kubeop-chart
version: 0.1.0
source: https://github.com/vivdalal/team2-kubeop 
maintainers:
  - email: dalal.vi@husky.neu.edu
    name: vivdalal
  - email: mandakathil.s@husky.neu.edu
    name: sreeragsreenath
  - email: kamlesh.r@husky.neu.edu
    name: riddhiKakadiya
  - email: soni.j@husky.neu.edu 
    name: jai-soni    
